# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhrasePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase_one', models.TextField()),
                ('phrase_two', models.TextField()),
                ('num', models.IntegerField()),
            ],
        ),
    ]
