# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruseng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrasepair',
            name='num',
            field=models.IntegerField(db_index=True),
        ),
    ]
